### ISSUE TITLE
how to custom keyboard's height?

### ISSUE THREAD

**Issue by ssshen** [themodernjavascript/react-native-custom-keyboard-kit#11]
when i set key height, the total height does not changed, as the pic show:
![image](https://user-images.githubusercontent.com/28528399/68370797-41364380-0178-11ea-8881-98b91488ba60.png)

**Comment by Bunlong** [comment]
@ssshen you have to set the container/wrapper height of the key too.

**Comment by ssshen** [comment]
@Bunlong thx, it works

**Comment by Bunlong** [comment]
@ssshen you are welcome. thx!
